In [31]:
import numpy as np

In [32]:
x = np.arange(4)
y = np.ones(5)
z = np.array([1., 2., 3., 4., 5.])

In [33]:
print(x.shape)
print(x)

(4,)
[0 1 2 3]


In [34]:
print(y.shape)
print(y)

(5,)
[1. 1. 1. 1. 1.]


In [35]:
print(xx.shape)
print(xx)

(4, 1)
[[0]
 [1]
 [2]
 [3]]


In [36]:
print(z.shape)
print(z)

(5,)
[1. 2. 3. 4. 5.]


In [37]:
op = (xx + z)
print(op.shape)
print(op)

(4, 5)
[[1. 2. 3. 4. 5.]
 [2. 3. 4. 5. 6.]
 [3. 4. 5. 6. 7.]
 [4. 5. 6. 7. 8.]]


In [48]:
points = np.array([[1, 2, 3, 4],
                   [5, 6, 7, 8],
                   [9, 10, 11, 12],
                   [13, 14, 15, 16],
                   [17, 18, 19, 20]])
centroids = np.array([[21, 22, 23, 24],
                      [25, 26, 27, 28]])
print(centroids.shape)
print(centroids[:,np.newaxis,:].shape)
print(points.shape)

(2, 4)
(2, 1, 4)
(5, 4)


In [53]:
broadcast_difference = centroids[:,np.newaxis] - points
print(broadcast_difference.shape)
broadcast_difference

(2, 5, 4)


array([[[20, 20, 20, 20],
        [16, 16, 16, 16],
        [12, 12, 12, 12],
        [ 8,  8,  8,  8],
        [ 4,  4,  4,  4]],

       [[24, 24, 24, 24],
        [20, 20, 20, 20],
        [16, 16, 16, 16],
        [12, 12, 12, 12],
        [ 8,  8,  8,  8]]])